export { default as Main } from "../src/components/header/main/Main";
export { default as Services } from "../src/components/services/Services";
export { default as About } from "../src/components/about/About";
export { default as Gallery } from "../src/components/gallery/Gallery";
export { default as Videos } from "../src/components/videos/Videos";
export { default as Testimonials } from "../src/components/testimonials/Testimonials";
export { default as ContactUs } from "../src/components/contact/ContactUs";
export { default as FormSection } from "../src/components/form/FormSection";
export { default as MapSection } from "../src/components/map/MapSection";
export { default as UsefulLinks } from "../src/components/usefullinks/UsefulLinks";
export { default as FooterSection } from "../src/components/footer/FooterSection";
export { default as ScrollTop } from "../src/components/scroll top/ScrollTop";  